branches:
  - main
  - semantic-release-setup
  
plugins:
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  - '@semantic-release/github'
  - - '@semantic-release/exec'
    - verifyReleaseCmd: 'echo version=${nextRelease.version} >> $GITHUB_OUTPUT'
