name: Deploy to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"

permissions:
  packages: write
  contents: write
  repository-projects: write

env:
  AUTOAPIGEN_CSPROJ: ${{ github.workspace }}/src/AutoApiGen/AutoApiGen.csproj
  ARTIFACTS_DIRECTORY: ${{ github.workspace }}/artifacts
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.8.1

    - name: Install Semantic Release Plugins
      run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec

    - name: Fetch Semantic Release Version
      run: npx semantic-release --dry-run

  deploy:
    runs-on: ubuntu-latest
    needs: fetch-version

    if: ${{ needs.fetch-version.outputs.version != "" }}
    env:
      VERSION: ${{ needs.fetch-version.outputs.version }}
    
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.0
      if: ${{ env.VERSION != "" }}
      
    - name: Restore dependencies
      run: dotnet restore ${{ env.AUTOAPIGEN_CSPROJ }}

    - name: Build
      run: dotnet build ${{ env.AUTOAPIGEN_CSPROJ }} -p:Version=${{ env.Version }} -p:AssemblyVersion=${{ env.Version }} --configuration Release --no-restore
    
    - name: Pack
      run: dotnet pack ${{ env.AUTOAPIGEN_CSPROJ }} --output ${{ env.ARTIFACTS_DIRECTORY }} -p:Version=${{ env.VERSION }} -p:AssemblyVersion=${{ env.Version }} --configuration Release --no-restore --no-build
    
    - name: Add Source
      run: dotnet nuget add source --name "github" --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Run Semantic Release
      run: npx -p semantic-release@13.1.1 -p @semantic-release/changelog@1.0.0 -p @semantic-release/git@3.0.0 -p @semantic-release/exec@2.0.0 semantic-release
      
