name: Deploy to GitHub Packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AUTOAPIGEN_CSPROJ: ${{ github.workspace }}/src/AutoApiGen/AutoApiGen.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.0
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Pack
      run: dotnet pack --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} 
    
    - name: Add Source
      run: dotnet nuget add source --username DanielGG1618 --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DanielGG1618/index.json"
   
    - name: Push
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --source "github"
