name: Deploy to GitHub Packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AUTOAPIGEN_CSPROJ: ${{ github.workspace }}/src/AutoApiGen/AutoApiGen.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.0
    - name: Restore dependencies
      run: dotnet restore ${{ env.AUTOAPIGEN_CSPROJ }}
      
    - name: Build
      run: dotnet build ${{ env.AUTOAPIGEN_CSPROJ }} --no-restore --configuration Release
    
    - name: Pack
      run: dotnet pack ${{ env.AUTOAPIGEN_CSPROJ }} --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} 
    
    - name: Add Source
      run: dotnet nuget add source --name "github" --username "${{ github.actor }}" --password "${{ secrets.PACKAGES_API_KEY }}" --store-password-in-clear-text "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Push to GitHub Packages
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --source "github" --skip-duplicate
