name: Run .NET Tests

on:
  push:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test ./tests/UnitTests/UnitTests.csproj --verbosity normal
